apiVersion: v1
kind: ServiceAccount
metadata:
  name: montecarlo-service
  namespace: montecarlo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: montecarlo-service
  namespace: montecarlo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["kubeflow.org"]
    resources: ["mpijobs"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: montecarlo-service
  namespace: montecarlo
subjects:
  - kind: ServiceAccount
    name: montecarlo-service
    namespace: montecarlo
roleRef:
  kind: Role
  name: montecarlo-service
  apiGroup: rbac.authorization.k8s.io
